routes/web.php
<?php
//Route::get('/', function () { return redirect('/admin/home'); });
Route::get('/admin', 'Admin\UsersController@index')->middleware('auth');
Route::get('/', 'HomeController@index')->name('/');
Route::get('/search', 'HomeController@search');//->middleware('auth');
Route::get('/restaurants', 'HomeController@categories');
Route::get('/kitchens', 'HomeController@categories');
Route::get('ajax_cats', 'HomeController@categories_ajax');
Route::get('/popular_orders', 'HomeController@popular_orders');
Route::get('/popluar_orders/get/{id}', 'HomeController@popular_orders_get');
Route::get('/category/{url}', 'HomeController@category_view');
Route::get('/category/{url}/{sub}', 'HomeController@category_view');
Route::get('/page/{page}', 'HomeController@page');
$this->get('cart-data', 'HomeController@cart_data');
$this->post('add-to-cart', 'HomeController@add_to_cart');
$this->get('clear-cart', 'HomeController@clear_cart');
$this->post('cart-plus-item', 'HomeController@cart_plus_item');
$this->post('cart-minus-item', 'HomeController@cart_minus_item');
$this->post('cart-delete-item', 'HomeController@cart_delete_item');
$this->get('checkout-cart', 'HomeController@checkout_cart');
$this->post('cart-submit', 'HomeController@submit_cart');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('products', 'Admin\ProductsController');
    Route::post('products_mass_destroy', ['uses' => 'Admin\ProductsController@massDestroy', 'as' => 'products.mass_destroy']);
    Route::post('products_restore/{id}', ['uses' => 'Admin\ProductsController@restore', 'as' => 'products.restore']);
    Route::delete('products_perma_del/{id}', ['uses' => 'Admin\ProductsController@perma_del', 'as' => 'products.perma_del']);
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories_mass_destroy', ['uses' => 'Admin\CategoriesController@massDestroy', 'as' => 'categories.mass_destroy']);
    Route::post('categories_restore/{id}', ['uses' => 'Admin\CategoriesController@restore', 'as' => 'categories.restore']);
    Route::delete('categories_perma_del/{id}', ['uses' => 'Admin\CategoriesController@perma_del', 'as' => 'categories.perma_del']);
    Route::resource('prices', 'Admin\PricesController');
    Route::post('prices_mass_destroy', ['uses' => 'Admin\PricesController@massDestroy', 'as' => 'prices.mass_destroy']);
    Route::post('prices_restore/{id}', ['uses' => 'Admin\PricesController@restore', 'as' => 'prices.restore']);
    Route::delete('prices_perma_del/{id}', ['uses' => 'Admin\PricesController@perma_del', 'as' => 'prices.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('orders', 'Admin\OrdersController');
    Route::post('orders_mass_destroy', ['uses' => 'Admin\OrdersController@massDestroy', 'as' => 'orders.mass_destroy']);
    Route::post('orders_restore/{id}', ['uses' => 'Admin\OrdersController@restore', 'as' => 'orders.restore']);

    Route::resource('pages', 'Admin\PagesController');
    Route::post('pages_mass_destroy', ['uses' => 'Admin\PagesController@massDestroy', 'as' => 'pages.mass_destroy']);
    Route::post('pages_restore/{id}', ['uses' => 'Admin\PagesController@restore', 'as' => 'pages.restore']);
 
});

app/Price.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Price
 *
 * @package App
 * @property string $guid
 * @property double $price
 * @property string $data
*/
class Price extends Model
{
    use SoftDeletes;

    protected $fillable = ['guid', 'price', 'data'];
    protected $hidden = [];
    
    

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setPriceAttribute($input)
    {
        if ($input != '') {
            $this->attributes['price'] = $input;
        } else {
            $this->attributes['price'] = null;
        }
    }
    
}

app/Http/Controllers/Admin/PricesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Price;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StorePricesRequest;
use App\Http\Requests\Admin\UpdatePricesRequest;

class PricesController extends Controller
{
    /**
     * Display a listing of Price.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('price_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('price_delete')) {
                return abort(401);
            }
            $prices = Price::onlyTrashed()->get();
        } else {
            $prices = Price::all();
        }

        return view('admin.prices.index', compact('prices'));
    }

    /**
     * Show the form for creating new Price.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('price_create')) {
            return abort(401);
        }
        return view('admin.prices.create');
    }

    /**
     * Store a newly created Price in storage.
     *
     * @param  \App\Http\Requests\StorePricesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePricesRequest $request)
    {
        if (! Gate::allows('price_create')) {
            return abort(401);
        }
        $price = Price::create($request->all());



        return redirect()->route('admin.prices.index');
    }


    /**
     * Show the form for editing Price.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('price_edit')) {
            return abort(401);
        }
        $price = Price::findOrFail($id);

        return view('admin.prices.edit', compact('price'));
    }

    /**
     * Update Price in storage.
     *
     * @param  \App\Http\Requests\UpdatePricesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePricesRequest $request, $id)
    {
        if (! Gate::allows('price_edit')) {
            return abort(401);
        }
        $price = Price::findOrFail($id);
        $price->update($request->all());



        return redirect()->route('admin.prices.index');
    }


    /**
     * Display Price.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('price_view')) {
            return abort(401);
        }
        $price = Price::findOrFail($id);

        return view('admin.prices.show', compact('price'));
    }


    /**
     * Remove Price from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('price_delete')) {
            return abort(401);
        }
        $price = Price::findOrFail($id);
        $price->delete();

        return redirect()->route('admin.prices.index');
    }

    /**
     * Delete all selected Price at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('price_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Price::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Price from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('price_delete')) {
            return abort(401);
        }
        $price = Price::onlyTrashed()->findOrFail($id);
        $price->restore();

        return redirect()->route('admin.prices.index');
    }

    /**
     * Permanently delete Price from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('price_delete')) {
            return abort(401);
        }
        $price = Price::onlyTrashed()->findOrFail($id);
        $price->forceDelete();

        return redirect()->route('admin.prices.index');
    }
}

app/Http/Controllers/Api/V1/PricesController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Price;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StorePricesRequest;
use App\Http\Requests\Admin\UpdatePricesRequest;

class PricesController extends Controller
{
    public function index()
    {
        return Price::all();
    }

    public function show($id)
    {
        return Price::findOrFail($id);
    }

    public function update(UpdatePricesRequest $request, $id)
    {
        $price = Price::findOrFail($id);
        $price->update($request->all());
        

        return $price;
    }

    public function store(StorePricesRequest $request)
    {
        $price = Price::create($request->all());
        

        return $price;
    }

    public function destroy($id)
    {
        $price = Price::findOrFail($id);
        $price->delete();
        return '';
    }
}

resources/views/admin/prices/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.prices.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.prices.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('guid', trans('quickadmin.prices.fields.guid').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('guid', old('guid'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('guid'))
                        <p class="help-block">
                            {{ $errors->first('guid') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('price', trans('quickadmin.prices.fields.price').'', ['class' => 'control-label']) !!}
                    {!! Form::text('price', old('price'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('data', trans('quickadmin.prices.fields.data').'', ['class' => 'control-label']) !!}
                    {!! Form::text('data', old('data'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('data'))
                        <p class="help-block">
                            {{ $errors->first('data') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/prices/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.prices.title')</h3>
    
    {!! Form::model($price, ['method' => 'PUT', 'route' => ['admin.prices.update', $price->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('guid', trans('quickadmin.prices.fields.guid').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('guid', old('guid'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('guid'))
                        <p class="help-block">
                            {{ $errors->first('guid') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('price', trans('quickadmin.prices.fields.price').'', ['class' => 'control-label']) !!}
                    {!! Form::text('price', old('price'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('data', trans('quickadmin.prices.fields.data').'', ['class' => 'control-label']) !!}
                    {!! Form::text('data', old('data'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('data'))
                        <p class="help-block">
                            {{ $errors->first('data') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/prices/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.prices.title')</h3>
    @can('price_create')
    <p>
        <a href="{{ route('admin.prices.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    @can('price_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.prices.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.prices.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($prices) > 0 ? 'datatable' : '' }} @can('price_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('price_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.prices.fields.guid')</th>
                        <th>@lang('quickadmin.prices.fields.price')</th>
                        <th>@lang('quickadmin.prices.fields.data')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($prices) > 0)
                        @foreach ($prices as $price)
                            <tr data-entry-id="{{ $price->id }}">
                                @can('price_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='guid'>{{ $price->guid }}</td>
                                <td field-key='price'>{{ $price->price }}</td>
                                <td field-key='data'>{{ $price->data }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('price_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.prices.restore', $price->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('price_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.prices.perma_del', $price->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('price_view')
                                    <a href="{{ route('admin.prices.show',[$price->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('price_edit')
                                    <a href="{{ route('admin.prices.edit',[$price->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('price_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.prices.destroy', $price->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('price_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.prices.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

resources/views/admin/prices/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.prices.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.prices.fields.guid')</th>
                            <td field-key='guid'>{{ $price->guid }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.prices.fields.price')</th>
                            <td field-key='price'>{{ $price->price }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.prices.fields.data')</th>
                            <td field-key='data'>{{ $price->data }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.prices.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop