routes/web.php
<?php
//Route::get('/', function () { return redirect('/admin/home'); });
Route::get('/admin', 'Admin\UsersController@index')->middleware('auth');
Route::get('/', 'HomeController@index')->name('/');
Route::get('/search', 'HomeController@search');//->middleware('auth');
Route::get('/restaurants', 'HomeController@categories');
Route::get('/kitchens', 'HomeController@categories');
Route::get('ajax_cats', 'HomeController@categories_ajax');
Route::get('/popular_orders', 'HomeController@popular_orders');
Route::get('/popluar_orders/get/{id}', 'HomeController@popular_orders_get');
Route::get('/category/{url}', 'HomeController@category_view');
Route::get('/category/{url}/{sub}', 'HomeController@category_view');
Route::get('/page/{page}', 'HomeController@page');
$this->get('cart-data', 'HomeController@cart_data');
$this->post('add-to-cart', 'HomeController@add_to_cart');
$this->get('clear-cart', 'HomeController@clear_cart');
$this->post('cart-plus-item', 'HomeController@cart_plus_item');
$this->post('cart-minus-item', 'HomeController@cart_minus_item');
$this->post('cart-delete-item', 'HomeController@cart_delete_item');
$this->get('checkout-cart', 'HomeController@checkout_cart');
$this->post('cart-submit', 'HomeController@submit_cart');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('products', 'Admin\ProductsController');
    Route::post('products_mass_destroy', ['uses' => 'Admin\ProductsController@massDestroy', 'as' => 'products.mass_destroy']);
    Route::post('products_restore/{id}', ['uses' => 'Admin\ProductsController@restore', 'as' => 'products.restore']);
    Route::delete('products_perma_del/{id}', ['uses' => 'Admin\ProductsController@perma_del', 'as' => 'products.perma_del']);
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories_mass_destroy', ['uses' => 'Admin\CategoriesController@massDestroy', 'as' => 'categories.mass_destroy']);
    Route::post('categories_restore/{id}', ['uses' => 'Admin\CategoriesController@restore', 'as' => 'categories.restore']);
    Route::delete('categories_perma_del/{id}', ['uses' => 'Admin\CategoriesController@perma_del', 'as' => 'categories.perma_del']);
    Route::resource('prices', 'Admin\PricesController');
    Route::post('prices_mass_destroy', ['uses' => 'Admin\PricesController@massDestroy', 'as' => 'prices.mass_destroy']);
    Route::post('prices_restore/{id}', ['uses' => 'Admin\PricesController@restore', 'as' => 'prices.restore']);
    Route::delete('prices_perma_del/{id}', ['uses' => 'Admin\PricesController@perma_del', 'as' => 'prices.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::resource('orders', 'Admin\OrdersController');
    Route::post('orders_mass_destroy', ['uses' => 'Admin\OrdersController@massDestroy', 'as' => 'orders.mass_destroy']);
    Route::post('orders_restore/{id}', ['uses' => 'Admin\OrdersController@restore', 'as' => 'orders.restore']);

    Route::resource('pages', 'Admin\PagesController');
    Route::post('pages_mass_destroy', ['uses' => 'Admin\PagesController@massDestroy', 'as' => 'pages.mass_destroy']);
    Route::post('pages_restore/{id}', ['uses' => 'Admin\PagesController@restore', 'as' => 'pages.restore']);
 
});

app/Category.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Category
 *
 * @package App
 * @property integer $basecode
 * @property string $guid
 * @property string $name
 * @property double $mindeliveryordersum
 * @property double $deliverysum
 * @property integer $deliverytime
 * @property time $opentime
 * @property time $closetime
 * @property tinyInteger $monworkingday
 * @property tinyInteger $tueworkingday
 * @property tinyInteger $wedworkingday
 * @property tinyInteger $thuworkingday
 * @property tinyInteger $friworkingday
 * @property tinyInteger $satworkingday
 * @property tinyInteger $sunworkingday
 * @property string $logo
*/
class Category extends Model
{
    use SoftDeletes;

    protected $fillable = ['basecode', 'guid', 'name', 'url', 'mindeliveryordersum', 'deliverysum', 'deliverytime', 'opentime', 'closetime', 'monworkingday', 'tueworkingday', 'wedworkingday', 'thuworkingday', 'friworkingday', 'satworkingday', 'sunworkingday', 'logo'];
    protected $hidden = [];
    

    public function generateWorkingDays() {

        $arr = [];
        $arr['пн'] = $this->monworkingday;
        $arr['вт'] = $this->tueworkingday;
        $arr['ср'] = $this->wedworkingday;
        $arr['чт'] = $this->thuworkingday;
        $arr['пт'] = $this->friworkingday;
        $arr['сб'] = $this->satworkingday;
        $arr['вс'] = $this->sunworkingday;
        $str = '';
        $i = 0;
        $c = count($arr);
        foreach($arr as $key => $a)
        {
            if($a)
            {

                if($c == $i + 1)
                {
                    $str .= $key;
                }
                else
                {
                    $str .= $key.', ';
                }

            }
            $i++;
        }

       return $str;


    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setBasecodeAttribute($input)
    {
        $this->attributes['basecode'] = $input ? $input : null;
    }

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setMindeliveryordersumAttribute($input)
    {
        if ($input != '') {
            $this->attributes['mindeliveryordersum'] = $input;
        } else {
            $this->attributes['mindeliveryordersum'] = null;
        }
    }

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setDeliverysumAttribute($input)
    {
        if ($input != '') {
            $this->attributes['deliverysum'] = $input;
        } else {
            $this->attributes['deliverysum'] = null;
        }
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setDeliverytimeAttribute($input)
    {
        $this->attributes['deliverytime'] = $input ? $input : null;
    }

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setOpentimeAttribute($input)
    {
        if ($input != null && $input != '') {
            $this->attributes['opentime'] = Carbon::createFromFormat('H:i:s', $input)->format('H:i:s');
        } else {
            $this->attributes['opentime'] = null;
        }
    }

    /**
     * Get attribute from date format
     * @param $input
     *
     * @return string
     */
    public function getOpentimeAttribute($input)
    {
        if ($input != null && $input != '') {
            return Carbon::createFromFormat('H:i:s', $input)->format('H:i:s');
        } else {
            return '';
        }
    }

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setClosetimeAttribute($input)
    {
        if ($input != null && $input != '') {
            $this->attributes['closetime'] = Carbon::createFromFormat('H:i:s', $input)->format('H:i:s');
        } else {
            $this->attributes['closetime'] = null;
        }
    }

    /**
     * Get attribute from date format
     * @param $input
     *
     * @return string
     */
    public function getClosetimeAttribute($input)
    {
        if ($input != null && $input != '') {
            return Carbon::createFromFormat('H:i:s', $input)->format('H:i:s');
        } else {
            return '';
        }
    }

    public function products()
    {

        return $this->hasMany(Product::class, 'parentguid_id', 'guid')->where('isgroup', 0)->withoutTrashed();
    }
    public function foodTypes()
    {
        return $this->hasMany(CategoryType::class, 'guid', 'guid')->where('type', 'food')->get();
    }
    public function kitchenTypes()
    {
        return $this->hasMany(CategoryType::class, 'guid', 'guid')->where('type', 'kitchen')->get();
    }
    
}

app/CategoryType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CategoryType extends Model
{
    //
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCategoriesRequest;
use App\Http\Requests\Admin\UpdateCategoriesRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class CategoriesController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Category.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('category_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('category_delete')) {
                return abort(401);
            }
            $categories = Category::onlyTrashed()->get();
        } else {
            $categories = Category::all();
        }

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating new Category.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('category_create')) {
            return abort(401);
        }
        return view('admin.categories.create');
    }

    /**
     * Store a newly created Category in storage.
     *
     * @param  \App\Http\Requests\StoreCategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoriesRequest $request)
    {
        if (! Gate::allows('category_create')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $category = Category::create($request->all());



        return redirect()->route('admin.categories.index');
    }


    /**
     * Show the form for editing Category.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('category_edit')) {
            return abort(401);
        }
        $category = Category::findOrFail($id);

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update Category in storage.
     *
     * @param  \App\Http\Requests\UpdateCategoriesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriesRequest $request, $id)
    {
        if (! Gate::allows('category_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $category = Category::findOrFail($id);
        $category->update($request->all());



        return redirect()->route('admin.categories.index');
    }


    /**
     * Display Category.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('category_view')) {
            return abort(401);
        }
        $products = \App\Product::where('parentguid_id', $id)->get();

        $category = Category::findOrFail($id);

        return view('admin.categories.show', compact('category', 'products'));
    }


    /**
     * Remove Category from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('category_delete')) {
            return abort(401);
        }
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->route('admin.categories.index');
    }

    /**
     * Delete all selected Category at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('category_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Category::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Category from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('category_delete')) {
            return abort(401);
        }
        $category = Category::onlyTrashed()->findOrFail($id);
        $category->restore();

        return redirect()->route('admin.categories.index');
    }

    /**
     * Permanently delete Category from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('category_delete')) {
            return abort(401);
        }
        $category = Category::onlyTrashed()->findOrFail($id);
        $category->forceDelete();

        return redirect()->route('admin.categories.index');
    }
}

app/Http/Controllers/Api/V1/CategoriesController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCategoriesRequest;
use App\Http\Requests\Admin\UpdateCategoriesRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class CategoriesController extends Controller
{
    use FileUploadTrait;

    public function index()
    {
        return Category::all();
    }

    public function show($id)
    {
        return Category::findOrFail($id);
    }

    public function update(UpdateCategoriesRequest $request, $id)
    {
        $request = $this->saveFiles($request);
        $category = Category::findOrFail($id);
        $category->update($request->all());
        

        return $category;
    }

    public function store(StoreCategoriesRequest $request)
    {
        $request = $this->saveFiles($request);
        $category = Category::create($request->all());
        

        return $category;
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return '';
    }
}

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.categories.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.categories.fields.basecode')</th>
                            <td field-key='basecode'>{{ $category->basecode }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.guid')</th>
                            <td field-key='guid'>{{ $category->guid }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.name')</th>
                            <td field-key='name'>{{ $category->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.mindeliveryordersum')</th>
                            <td field-key='mindeliveryordersum'>{{ $category->mindeliveryordersum }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.deliverysum')</th>
                            <td field-key='deliverysum'>{{ $category->deliverysum }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.deliverytime')</th>
                            <td field-key='deliverytime'>{{ $category->deliverytime }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.opentime')</th>
                            <td field-key='opentime'>{{ $category->opentime }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.closetime')</th>
                            <td field-key='closetime'>{{ $category->closetime }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.monworkingday')</th>
                            <td field-key='monworkingday'>{{ Form::checkbox("monworkingday", 1, $category->monworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.tueworkingday')</th>
                            <td field-key='tueworkingday'>{{ Form::checkbox("tueworkingday", 1, $category->tueworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.wedworkingday')</th>
                            <td field-key='wedworkingday'>{{ Form::checkbox("wedworkingday", 1, $category->wedworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.thuworkingday')</th>
                            <td field-key='thuworkingday'>{{ Form::checkbox("thuworkingday", 1, $category->thuworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.friworkingday')</th>
                            <td field-key='friworkingday'>{{ Form::checkbox("friworkingday", 1, $category->friworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.satworkingday')</th>
                            <td field-key='satworkingday'>{{ Form::checkbox("satworkingday", 1, $category->satworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.sunworkingday')</th>
                            <td field-key='sunworkingday'>{{ Form::checkbox("sunworkingday", 1, $category->sunworkingday == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.categories.fields.logo')</th>
                            <td field-key='logo'>@if($category->logo)<a href="{{ env('APP_URL') . '/public/uploads/logos/'.$category->logo }}" target="_blank"><img src="{{ env('APP_URL') . '/public/uploads/logos/'.$category->logo }}"/></a>@endif</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#products" aria-controls="products" role="tab" data-toggle="tab">Products</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="products">
<table class="table table-bordered table-striped {{ count($products) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.products.fields.guid')</th>
                        <th>@lang('quickadmin.products.fields.name')</th>
                        <th>@lang('quickadmin.products.fields.isgroup')</th>
                        <th>@lang('quickadmin.products.fields.isdeleted')</th>
                        <th>@lang('quickadmin.products.fields.parentguid')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($products) > 0)
            @foreach ($products as $product)
                <tr data-entry-id="{{ $product->id }}">
                    <td field-key='guid'>{{ $product->guid }}</td>
                                <td field-key='name'>{{ $product->name }}</td>
                                <td field-key='isgroup'>{{ Form::checkbox("isgroup", 1, $product->isgroup == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='isdeleted'>{{ Form::checkbox("isdeleted", 1, $product->isdeleted == 1 ? true : false, ["disabled"]) }}</td>
                                <td field-key='parentguid'>{{ $product->parentguid->guid or '' }}</td>
                                <td field-key='photos'>@if($product->photos)<a href="{{ asset(env('UPLOAD_PATH').'/' . $product->photos) }}" target="_blank"><img src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $product->photos) }}"/></a>@endif</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('product_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.restore', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('product_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.perma_del', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('product_view')
                                    <a href="{{ route('admin.products.show',[$product->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('product_edit')
                                    <a href="{{ route('admin.products.edit',[$product->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('product_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.destroy', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="11">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.categories.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop